
export const projects = [

    {
        id: 1,
        title: "Airtistic",
        subtitle: "AI Images Generator",
        technology: ['HTML', 'Tailwind', 'Javascript', 'React', 'NodeJS', 'Express']  ,
        en:"Airtistic is an app that allows you to generate images using DALL-E AI. It is an application connected to the OpenAI API. My first project in which I put my React skills to the test. It has a backend developed mainly with NodeJS, Express, Cloudinary and MongoDB allowing users not only to generate images but also to share them with others as these images appear in the Homepage arranged as a showcase.",
        es: "Airtistic es una app que te permite generar imagénes usando la IA de DALL-E. Se trata de una aplicación conectada a la API de OpenAI. Mi primer proyecto en el que pongo a prueba mis conocimientos de React. Cuenta con un backend desarrollado principalmente con NodeJS, Express, Cloudinary y MongoDB permitiendo a los usuarios no solo generar imágenes si no compartirlos con los demás ya que estas imágenes aparecen en la Home dispuesta en forma de escaparate.",
        image: "../../assets/images/airtistic.png",
        linkOne: "https://github.com/kervinmarquinez/airtistic",
        linkTwo: "https://luminous-malasada-3a2c47.netlify.app/"  
    },
    {
        id: 2,
        title: "Footure",
        subtitle: "Single Product Page" ,
        technology: ['HTML', 'SASS', 'Javascript'] ,
        en:"To put into practice what I learned during the Master's Degree in Web Design and Development, I decided to create a single product page focused on the sale of futuristic trainers. It is a basic page in which the images have been generated by the Midjourney AI. The technologies used are mainly HTML and SASS.",
        es: "Para poner en práctica lo aprendido durante el Máster de Diseño y Desarrollo Web, decidí crear una single product page enfocada en la venta de unas zapatillas futurísticas. Se trata de una página básica en el que las imágenes han sido generadas por la IA de Midjourney. Las tecnologías usadas son principalmente, HTML y SASS.",
        image: "../../assets/images/footure.png",
        linkOne: "https://github.com/kervinmarquinez/footure",
        linkTwo: "https://kervinmarquinez.github.io/footure/src/index.html"  
    },
    {
        id: 3,
        title: "Drop",
        subtitle: "Esports Magazine" ,
        technology: ['HTML', 'CSS', 'Javascript'] ,
        en:"Final project of the Master's Degree in Web Design and Development that I did. Drop is an online magazine focused on news and interviews about everything related to the world of esports. In this project we had to meet a series of requirements to pass the course; create a homepage, a category section, a contact page and the entry of an article.",
        es: "Proyecto final del Máster de Diseño y Desarrollo Web que realicé. Drop es una revista online enfocada en noticias y entrevistas de todo lo relacionado con el mundo de los esports. En este proyecto teníamos que cumplir una serie de requisitos para aprobar la asignatura; crear una Homepage, una sección de categorías, una página de contacto y la entrada de un artículo.",
        image: "../../assets/images/drop.jpg",
        linkOne: "https://github.com/kervinmarquinez/dropmagazine",
        linkTwo: "https://kervinmarquinez.github.io/dropmagazine/"  
    },
    {
        id: 4,
        title: "GIF Generator",
        subtitle: "GIPHY API" ,
        technology: ['HTML', 'Tailwind CSS', 'Javascript', 'React'] ,
        en:"It's a simple app connected to the GIPH API through a fetch. For this project I decided to use Tailwind CSS for the styling as I hadn't experimented with it yet and wanted to try it out.",
        es: "Es una app sencilla conectada con la API de GIPHY a través de un fetch. Para este proyecto decidí usar Tailwind CSS para los estilos ya que todavía no había experimentado con ella y quería probarla. ",
        image: "../../assets/images/gif.jpg",
        linkOne: "https://github.com/kervinmarquinez/react-gifs-generator",
        linkTwo: "https://kervinmarquinez.github.io/react-gifs-generator/"  
    },
    {
        id: 5,
        title: "Conecta 4",
        subtitle: "Game" ,
        technology: ['HTML', 'CSS', 'Javascript', 'React'] ,
        en:"One of my most recent projects. To put my current knowledge and programming logic into practice, I decided to create this classic game where to win you have to connect four tiles of the same colour horizontally, vertically or diagonally. It is a project where the use of React's useState is predominant.",
        es: "Uno de mis proyectos más recientes. Para poner en práctica mis conocimientos actuales y mi lógica programación decidí crear este clásico juego donde para ganar hay que conectar cuatro fichas del mismo color de forma horizontal, vertical o diagonal. Se trata de un proyecto en el que predomina el empleo del useState de React.",
        image: "../../assets/images/conecta4.jpg",
        linkOne: "https://github.com/kervinmarquinez/conecta4",
        linkTwo: "https://kervinmarquinez.github.io/conecta4/"  
    },
    {
        id: 6,
        title: "Christmas Wishlist",
        subtitle: "TO-DO List" ,
        technology: ['HTML', 'SASS', 'Bootstrap', 'Javascript'] ,
        en:"I wanted to give a different touch to the typical TO-DO List project. To do so, taking advantage of the time of the year I decided to develop it, I gave it a Christmas focus. In this app, the user can add and remove all those gifts he wants for this Christmas season. Basically, their wish list. Ho-ho-ho!",
        es: "Quería darle un toque distinto al típico proyecto de TO-DO List. Para ello, aprovechando la época en la que decidí desarrollarlo, le di un enfoque navideño. En esta app, el usuario puede añadir y eliminar todos aquellos regalos que quiere para esta época navideña. Básicamente, su lista de deseos. Ho-ho-ho!",
        image: "../../assets/images/christmas.jpg",
        linkOne: "https://github.com/kervinmarquinez/christmas_wishlist",
        linkTwo: "https://kervinmarquinez.github.io/christmas_wishlist/src/index.html"  
    },
    {
        id: 7,
        title: "Travel Agency",
        subtitle: "Course Project" ,
        technology: ['HTML', 'CSS', 'Bootstrap', 'Javascript', 'NodeJS', 'Express', 'MySQL'] ,
        en:"This is a project I did during a Udemy course. The aim was to put my Javascript skills into practice to create a fictitious travel agency. For the backend, we used technologies such as NodeJS and Express.",
        es: "Se trata de un proyecto que realicé durante un curso de Udemy. El objetivo era poner en práctica conocimientos de Javascript para crear una agencia de viajes ficticia. Para la parte del backend, empleamos tecnologías como NodeJS y Express.",
        image: "../../assets/images/viajes.jpg",
        linkOne: "https://github.com/kervinmarquinez/agenciaViajesNode",
        linkTwo: "" 
    },
    {
        id: 8,
        title: "Portfolio",
        subtitle: "Projects Portfolio" ,
        technology: ['HTML', 'Tailwind CSS', 'Javascript', 'React'] ,
        en:"This portfolio was created mainly with the aim of showing my profile and my knowledge through the different projects that I have been doing during all this learning process. For its development, I decided to use some of the most demanded technologies such as React and Tailwind CSS as well as different libraries. This is how a fully responsive portfolio was born.",
        es: "Este portfolio se creó principalmente con el objetivo de mostrar mi perfil y mis conocimientos a través de los distintos proyectos que he estado realizando durante todo este proceso de aprendizaje. Para su desarrollo, decidí usar algunas de las tecnologías mas demandadas del momento como React y Tailwind CSS además de distintas librerias. De esta forma nace un portfolio totalmente responsive.",
        image: "../../assets/images/portfolio.jpg",
        linkOne: "https://github.com/kervinmarquinez/portfolio",
        linkTwo: ""  
    },
]